# Basic
title: 心晴客栈
subtitle: 既往不恋，纵情向前
welcome_message:开开心心每一天
description: 小说和人生都是大梦一场。
creator: <a href="http://blog.yonghappy.com">@yonghappy</a>

url: "https://blog.yonghappy.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://blog.yonghappy.com'}
    

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
   
    github: yonghappy
    mail: nate@yongha

# Google Analytics
ga:
    id: 
    host: 
